version: '3'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - .env
      

volumes:
  postgres_data:
