# Generated by Django 4.2.1 on 2023-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0005_pickuprequest_price_alter_pickuprequest_order_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_type',
            field=models.CharField(choices=[('Waste', 'Waste'), ('Scrap', 'Scrap')], max_length=10),
        ),
    ]
