# Generated by Django 4.2.1 on 2023-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_remove_item_image_alter_pickuprequest_pickup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='Order_month',
            new_name='pickup_day',
        ),
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='Order_year',
            new_name='pickup_year',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='Order_day',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_month',
            field=models.IntegerField(default=6),
        ),
    ]
