# Generated by Django 4.2.1 on 2023-06-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0007_rename_order_month_pickuprequest_pickup_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_day',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_latitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_longitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
