# Generated by Django 4.2.1 on 2023-06-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_signup_day'),
        ('pickup', '0008_alter_pickuprequest_pickup_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_day',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='PickupTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waste_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', models.IntegerField(default=6)),
                ('year', models.IntegerField(default=2023)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
