# Generated by Django 4.2.1 on 2023-05-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_scrap_rename_waste_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
