# Generated by Django 4.2.1 on 2023-06-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=2, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_month',
            field=models.CharField(default=6, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_year',
            field=models.CharField(default=2023, max_length=50),
        ),
    ]
