# Generated by Django 4.2.1 on 2023-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_address_state_city_district_district_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
