# Generated by Django 4.2.1 on 2023-05-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_waste_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
