# Generated by Django 4.2.1 on 2023-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_waste_is_active_waste_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='description',
            new_name='best_use',
        ),
        migrations.AddField(
            model_name='waste',
            name='thickness',
            field=models.CharField(default='4’ x 8’, ½” thick', max_length=100),
        ),
    ]
