# Generated by Django 4.2.1 on 2023-05-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='category',
        ),
        migrations.AddField(
            model_name='scrap',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrap.scrapcategory'),
        ),
    ]
