# Generated by Django 4.2.1 on 2023-05-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ScrapCategory',
        ),
    ]
