# Generated by Django 4.2.1 on 2023-05-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_remove_scrap_category_scrap_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='image',
            field=models.ImageField(blank=True, upload_to='scrap_images/'),
        ),
    ]
