# Generated by Django 4.2.1 on 2023-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0002_rename_category_scrapcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='image',
            field=models.ImageField(upload_to='scrap_images/'),
        ),
    ]
