# Generated by Django 4.2.1 on 2023-05-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_address_name'),
        ('waste', '0002_remove_waste_category_delete_wastecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('additional_notes', models.TextField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.waste')),
            ],
        ),
    ]
