# Generated by Django 4.2.1 on 2023-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_month',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_year',
            field=models.IntegerField(default=2023),
        ),
    ]
