# Generated by Django 4.2.1 on 2023-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_day',
            field=models.IntegerField(default=8),
        ),
    ]
